### ISSUE TITLE
Retrieve slide fragment from IntroActivity

### ISSUE THREAD

**Issue by dasouza** [PaoloRotolo/AppIntro#16]
I'm using AppIntro to make a configuration wizard for my app. In order to do that I added a few widgets to my slide fragment layouts (i.e. a datepicker) and now I'm trying to get and save its values in the onDonePressed method of my IntroActivity. 

Since every variable in the AppIntro class is private and there are no getters... is there a way to do this?

Thank you.

**Comment by MacroYau** [comment]
I've just made a PR (#21) to add getters for fragments.

**Comment by dasouza** [comment]
Thank you, @MacroYau

I'm quite new to Android development so it may be my fault, but I still can´t retrieve the fragments, even if I use the `getSlides()` method. 

In my IntroActivity I have the following:

    @Override
    public void onDonePressed() {
        List<Fragment> fragments = getSlides();

        NumberPicker numberPicker = (NumberPicker)fragments.get(0).getView().findViewById(R.id.numberPicker);
    }

I'm getting this error:

> java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference

Can this be done after #21? 
Am I doing something wrong?

**Comment by PaoloRotolo** [comment]
Hey @dasouza. I've just released version 2.0.0.
**getSlides()** should work now.

**Comment by dasouza** [comment]
I'm still getting the `NullPointerException` using the same code as in my previous reply. However, I managed to solve my problem by creating a `saveData()` method in the slide `Fragment` class.

In case somebody else is facing the same issue, this is how my `onDonePressed()` looks now:

    @Override
    public void onDonePressed() {
        List<Fragment> fragments = getSlides();

        IntroFirstFragment firstFragment = (IntroFirstFragment) fragments.get(0);

        firstFragment.saveData();
    }


Thanks @PaoloRotolo. Keep the good work!

**Comment by PaoloRotolo** [comment]
@dasouza thank you for sharing the code :)
